### ISSUE TITLE
番剧解析好像用不了了？

### ISSUE THREAD

**Issue by MoeclubM** [AiMuC/BiliVideoDownload#1]
api可以用，能返回，但php返回不了

**Comment by AiMuC** [comment]
> api可以用，能返回，但php返回不了

明天看看问题发个新版

**Comment by AiMuC** [comment]
![image](https://user-images.githubusercontent.com/31570354/174283875-27155035-520b-471c-8ec3-970d1cc8caf0.png)
应该是Cookie设置的问题 直接从控制台复制出来后{}没有转码     可以使用fd抓包发送的cookie直接使用即可 或者手动吧那几个字符串转码一下就好了

**Comment by AiMuC** [comment]
http://www.jsons.cn/urlencode/    吧json的这一段单独复制出来转码后粘贴回去也能解决
![image](https://user-images.githubusercontent.com/31570354/174284402-d8eccf90-6e74-4e83-9aaf-4a00a99ecb78.png)

**Comment by MoeclubM** [comment]
ok 我去试试
